[package]
name = "template-node-runtime-wasm"
version = "0.9.0"
authors = ["Parity Technologies <admin@parity.io>"]

[lib]
name = "template_node_runtime"
crate-type = ["cdylib"]

[dependencies]
template-node-runtime = { path = "..", default-features = false }

[features]
default = []
std = [
	"template-node-runtime/std"
]

[profile.release]
panic = "abort"
lto = true

[workspace]
members = []
